import os
import re
import json

data_dir = r"e:\Projects\Personal\personal-notes\life\reading_list\app\data"
stats_file = r"e:\Projects\Personal\personal-notes\life\reading_list\app\data\book_stats.js"

word_counts = {}

# Fallback estimates for books that don't have text files yet
estimated_counts = {
    'plato-euthyphro': 5000,
    'plato-crito': 4000,
    'plato-charmides': 8000,
    'plato-laches': 7000,
    'plato-lysis': 6500,
    'plato-ion': 4500,
    'plato-hippias-major': 9000,
    'plato-hippias-minor': 5000,
    'plato-menexenus': 6000,
    'plato-euthydemus': 14000,
    'plato-protagoras': 22000,
    'plato-gorgias': 35000,
    'plato-meno': 14000,
    'plato-cratylus': 23000,
    'plato-symposium': 18000,
    'plato-phaedrus': 22000,
    'plato-parmenides': 25000,
    'plato-theaetetus': 28000,
    'plato-sophist': 22000,
    'plato-statesman': 23000,
    'plato-philebus': 20000,
    'plato-epistles': 20000,
    'aristotle-categories': 12000,
    'aristotle-interpretation': 8000,
    'aristotle-prior-analytics': 30000,
    'aristotle-posterior-analytics': 28000,
    'aristotle-topics': 40000,
    'aristotle-sophistical-refutations': 15000,
    'aristotle-physics': 70000,
    'aristotle-heavens': 40000,
    'aristotle-generation': 25000,
    'aristotle-meteorology': 30000,
    'aristotle-soul': 25000,
    'aristotle-parva': 20000,
    'aristotle-history-animals': 130000,
    'aristotle-parts-animals': 40000,
    'aristotle-movement-animals': 8000,
    'aristotle-progression-animals': 10000,
    'aristotle-generation-animals': 60000,
    'aristotle-metaphysics': 85000,
    'aristotle-eudemian': 45000,
    'aristotle-magna': 30000,
    'aristotle-constitution': 25000,
    'seneca-letters': 130000,
    'seneca-brevity': 12000,
    'seneca-happy': 15000,
    'aurelius-meditations': 25000,
    'epictetus-enchiridion': 6000,
    'epictetus-discourses': 45000,
    'augustine-confessions': 120000,
    'augustine-city': 350000,
    'macdonald-homeric-epics': 60000,
    'macdonald-myth': 65000,
    'barnea-yahweh': 50000,
    'barnea-origins': 55000,
    'gmirkin-berossus': 80000,
    'gmirkin-plato': 85000,
    'livesey-galatians': 40000,
    'adler-origins': 75000
}

for filename in os.listdir(data_dir):
    if filename.endswith(".js") and filename != "book_stats.js":
        filepath = os.path.join(data_dir, filename)
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
            
            # Find the book id
            match_id = re.search(r'window\.bookDataCache\["(.*?)"\]', content)
            if match_id:
                book_id = match_id.group(1)
                
                # Extract the JSON payload
                json_str = re.sub(r'^window\.bookDataCache\[.*?\]\s*=\s*', '', content).strip()
                if json_str.endswith(';'):
                    json_str = json_str[:-1]
                
                try:
                    data = json.loads(json_str)
                    words = data.get("text", "").split()
                    word_counts[book_id] = f"{len(words):,} words"
                except json.JSONDecodeError as e:
                    print(f"Error parsing {filename} as JSON: {e}")
                    # Fallback to roughly counting words in the file
                    words = content.split()
                    word_counts[book_id] = f"~{len(words):,} words"

# Merge estimates for books that weren't processed
for book_id, est_count in estimated_counts.items():
    if book_id not in word_counts:
        word_counts[book_id] = f"~{est_count:,} words (estimated)"

js_output = f"// Auto-generated by update_word_counts.py\nwindow.bookWordCounts = {json.dumps(word_counts, indent=4)};\n"
with open(stats_file, 'w', encoding='utf-8') as f:
    f.write(js_output)

print(f"Successfully processed {len(word_counts)} files and saved to {stats_file}")
